zsh/.zshrc:.zshrc
zsh/.zshenv:.zshenv
zsh/git_aliases.zsh:.config/zsh/git_aliases.zsh
zsh/more_customizations.zsh:.config/zsh/more_customizations.zsh
nvim:.config/nvim
ghostty:.config/ghostty
starship:.config/starship
karabiner:.config/karabiner
tmux/.tmux.conf:.tmux.conf
