brew "ripgrep"
brew "starship"
brew "neovim"
brew "fzf"
brew "lazygit"

# ZSH "plugins"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# FONTS
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-symbols-only-nerd-font"

# APPS
cask "ghostty"
cask "obsidian"
cask "karabiner-elements"
cask "rectangle"
